### ISSUE TITLE
Location permission

### ISSUE THREAD

**Issue by klemzy** [Polidea/RxAndroidBle#10]
I am just curious, why the library requires to have location permissions enabled in order to work?

Thanks!

**Comment by uKL** [comment]
Hey!

Starting from Android 6.0 it is required to hold **ACCESS_COARSE_LOCATION** or **ACCESS_FINE_LOCATION** in order to get scan results of device mac address. This is to strengthen user privacy. Even more, it is required that the user will have location services enabled.

You can read more [here](http://developer.android.com/reference/android/bluetooth/le/BluetoothLeScanner.html#startScan(java.util.List<android.bluetooth.le.ScanFilter>, android.bluetooth.le.ScanSettings, android.bluetooth.le.ScanCallback)).

**Comment by klemzy** [comment]
Hi,

I see, was not aware of that. Thanks!

-- 
Klemen
Sent with Airmail

On 7 April 2016 at 15:41:53, Paweł Urban (notifications@github.com) wrote:

Hey!

Starting from Android 6.0 it is required to hold ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION in order to get scan results of device mac address. This is to strengthen user privacy. Even more, it is required that the user will have location services enabled.

You can read more here.

**Comment by uKL** [comment]
We handle it internally (both permission and enabled state) and BleScanException is emitted with code LOCATION_PERMISSION_MISSING or LOCATION_SERVICES_DISABLED.

**Comment by mars3142** [comment]
And why don't you handle the "permission request" in your library? Do I have to handle by myself?

**Comment by uKL** [comment]
Yes, you should handle them by yourself. It would be hard to do it in the library because each application has it's own design. Making an universal one might not be the best idea.

There are libraries for Runtime Permissions that might be a good choice for you.

**Comment by MimgshuZhao** [comment]
I always get the hint: Location services needs to be enabled on Android 6.0
How can I enable the location services? 
Thanks

**Comment by MimgshuZhao** [comment]
Oh, never mind, I just enable it (By enable GPS...)
Thanks for the source anyway.
