### ISSUE TITLE
onClientConnectionState() - status=133 clientIf=6 device=F0:A3:23:3C:D6:EF

### ISSUE THREAD

**Issue by JiWenBo** [Polidea/RxAndroidBle#341]
How to solve this problem?status=133

**Comment by uKL** [comment]
Thanks for using the library. Error status 133 may have various reasons as it is a general error reported by the Android system.

It feels like it is a general question, if so please post a question on StackOverflow with #rxandroidble tag, otherwise feel free to reopen this issue with logs and more information.

For commercial support contact at hello@polidea.com
