### ISSUE TITLE
Compile errors in v. 1.10.2 

### ISSUE THREAD

**Issue by RobLewis** [Polidea/RxAndroidBle#627]
When I update my `rxandroidble-parent` project in Android Studio to v. 1.10.2, I get these "cannot resolve symbol" errors in the file `RxBleGattCallback.java`: `bleshadow` (lines 26 & 27), `Inject` (line 59), and `Named` (line 60). 

Everything else compiles OK.

**Comment by dariuszseweryn** [comment]
This seems to be related to https://github.com/johnrengelman/shadow/issues/264
I wish there would be a way to achieve it.

This seems to be an IDE / gradle issue. I have changed `settings.gradle` from:
```
include ':rxandroidble', ':dagger-compiler-shadow', ':dagger-library-shadow'
include ':sample', ':sample-kotlin', ':mockrxandroidble'

rootProject.name = 'rxandroidble-parent'
```
to
```
include ':dagger-compiler-shadow', ':dagger-library-shadow', ':rxandroidble'
include ':sample', ':sample-kotlin', ':mockrxandroidble'

rootProject.name = 'rxandroidble-parent'
```
And re-synced the project as IDE has suggested and the issue was gone. Once I did `File -> Invalidate Caches/Restart` the problem reappeared.

**Comment by RobLewis** [comment]
So all you did was change the order of the items in the first `include`? 
I don't really understand much about this but I note that the bug in `shadow` is almost 3 years old (or is it a JetBrains bug?). The project history shows that it was worked on as recently as 3 months ago so evidently it is being maintained.

**Comment by dariuszseweryn** [comment]
> So all you did was change the order of the items in the first `include`?

Yes but it only helped temporarily.
The project seems to be maintained but it seems that this issue is either complex to fix/workaround or not a big impact from the maintainers perspective.

Now it seems that a simple click on `Sync Project with Gradle Files` button solves the problem?
<img width="129" alt="Screenshot 2019-09-26 at 19 34 02" src="https://user-images.githubusercontent.com/1412475/65711248-cc5ded00-e094-11e9-93e1-05bc1cd3ee3f.png">
Dunno, either way I do not know what can I do on the this repository's side to help with the issue

**Comment by RobLewis** [comment]
I've tried updating to latest Android Studio and Gradle, editing `settings.gradle`, syncing project to Gradle files. Nothing changes the errors. 

Does this mean I'm going to get this same problem in other projects using the library?

**Comment by dariuszseweryn** [comment]
> Does this mean I'm going to get this same problem in other projects using the library?

No — this errors are visible only in the library project, not in the consumer application projects
