### ISSUE TITLE
Steps for OTA Update

### ISSUE THREAD

**Issue by sambhu815** [Polidea/RxAndroidBle#723]
Please help me to OTA (DFU) process
1) how to write  descriptor 
2) send indication
3) write characteristics
4) how to jump connected device into bootloader

connected BLE device to bootloader via sending indication and write characteristics with write descriptor.

Thank you

**Comment by dariuszseweryn** [comment]
Hello!

Thank you for using the library.

This is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/) rather than here — it is not inherently related to the usage of this library. You should consult the documentation of your peripheral as what you ask for will be device specific.

It should be possible to setup indications and write characteristic nevertheless. Indications are sent by the server to the client (central).

I am closing this as quite some time has already passed since the original post. If more info will be available I will try to help you.

Best Regards
