### ISSUE TITLE
Does it support onCharacteristicChanged?

### ISSUE THREAD

**Issue by tinybright** [Polidea/RxAndroidBle#8]
I read doc and haven't find onCharacteristicChanged.Does it support onCharacteristicChanged?

**Comment by mzgreen** [comment]
Yes it does. See https://github.com/Polidea/RxAndroidBle#change-notifications

**Comment by tinybright** [comment]
I overlooked it.

**Comment by xmbb** [comment]
i can't understand lambda, can you help to transform to normal

**Comment by dariuszseweryn** [comment]
Lambdas are just a syntax sugar. You can read about them here: https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html
You can find a lot of articles about lambdas on the Internet. ( https://blog.idrsolutions.com/2014/10/5-minutes-explanation-java-lambda-expression/ )

Long story short - instead of writing boilerplate in anonymous implementation of the interfaces with only one method / function you use lambda which is shorter to write.
